### ISSUE TITLE
[Feature Request] Retention of Only the Latest Backups Feature

### ISSUE THREAD

**Issue by k997** [jammsen/docker-palworld-dedicated-server#170]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Currently, the server creates regular backups but does not delete any previous backups, leading to an accumulation of redundant data over time. By specifying the desired number of backups to retain, users can ensure that storage space is not overwhelmed with outdated backups. Once the specified limit is reached, the server should automatically remove the oldest backups while retaining only the most recent ones.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by auxbh** [comment]
You can set "BACKUP_RETENTION_POLICY" in your default.env file to true then use "BACKUP_RETENTION_AMOUNT_TO_KEEP" to specify the number of backups to keep.

**Comment by k997** [comment]
thanks

**Comment by jammsen** [comment]
Hey @k997 
> Once the specified limit is reached, the server should automatically remove the oldest backups while retaining only the most recent ones.

No the server shouldnt do that, because the image introduced this feature. I even would have set the retention-polocy to default on and 30 files, IF i had introduce the feature completely in 1 patch. But i didnt, the feature was implemented and ask time by time. Thats why its off by default, because i dont want angry users issue, when i delete thoose precious savegames, without knowing anything about an infinity amount of setups. Saver way is to make this an option for you and you guys with the facts setup it up yourselfs.

Everything else is explained here: https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/README_ENV.md#container-settings
