### ISSUE TITLE
[Bug Report] RCON Yaml error when using server manual mode

### ISSUE THREAD

**Issue by robertlane** [jammsen/docker-palworld-dedicated-server#185]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When setting up my instance, I can't use the rcon built into the image when the server settings are set to manual instead of environment. As the yaml file is part of the image I also can not change the file due to permissions/persistence.

### Desired behavior

Use the env variables to still set the yaml file even if the PalWorldSettings.ini file is set to manual.

### To Reproduce

1. Start instance with 'manual' for settings
2. use docker to interact with bash
3. run rcon
4. error 'cli: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port'

### Software setup

- OS: Debian
- Docker:  24.0.7
- Portainer: 2.19.4

### Hardware setup

- CPU: i5-3470 
- RAM: 16G

**Comment by jammsen** [comment]
Hello @robertlane - First of im reallllyyyy confused here .....

This isnt a bug, you either go settings to auto mode and get everything configurated or you go manual and do **everything** yourself. This is **YOUR** choice. There is no in-between like an semi-auto. Its either A or B. One is new-user friendly and one is the advanced/pro-user approach, who knows how to get around.

So you did make a choice to do everything yourself, by choosing manual, your free to do that. 
As doing this is an advanced setting, i didnt expect to have to explain this, but by choosing this comes work too.

> When setting up my instance, I can't use the rcon built into the image when the server settings are set to manual instead of environment.

Thats not true, im listing in the software used in the readme at the bottom, it states the the rcon-cli is from https://github.com/gorcon/rcon-cli - Like reading on that page 15 seconds later in the examples i know that i can also use this with params like this: 
```shell
$ docker exec palworld-dedicated-server rcon -a 127.0.0.1:25575 -p adminPasswordHere1 info
Welcome to Pal Server[v0.1.4.0] jammsen.test.local
```
And it works just fine, just not without the alias and that elegantly ... 

> As the yaml file is part of the image I also can not change the file due to permissions/persistence.

Again also not true, you could just copy the rcon.yaml to your host via `docker cp palworld-dedicated-server:/home/steam/steamcmd/rcon.yaml /your/host/path/target/here`, now you have the file, configure it to your liking and then use a volume mount to that specific file like this:

```yaml
    volumes:
  ........
      - /yourpathhere/rcon.yaml:/home/steam/steamcmd/rcon.yaml 

OR

    volumes:
      - type: bind
        source: /yourpathhere/rcon.yaml
        target: /home/steam/steamcmd/rcon.yaml 

```
Remember to setup your permissions right!

_When bind-mounting a directory from the host in a container, files and directories maintain the permissions they have on the host. This is by design: when using a bind-mount, you're giving the container access to existing files from the host, and Docker won't make modifications to those files ..._ ( Source: https://stackoverflow.com/a/50325808 )

Im not sure what to make out of this, you "report a bug" here .... with statements that are not true, because the problems you are facing are solveable with like 15 seconds of google. What do you expect me to fix here? I dont see a bug here that needs fixing to be honest.

If you would have wrote an issue as a Feature Request to maybe have an "semi-auto-mode" or so, this would be a totally different story, but you choose "Bug Report" to report an error and i simply dont see one here. Please tell me if im missing something here ... im open to feedback ... but im getting the feeling you wanted to go manual, but didnt have the experience around Docker to really do it? 😕 ❓

**Comment by robertlane** [comment]
Hi @jammsen  - First off, thank you for this project, it has been very helpful.

I realized while re-reading this I did leave out some info, my apologies. I was concerned about the internal scripts requiring rcon not firing off. I have a log full of them.

`time="2024-02-09T08:00:06-06:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=6 job.command=/backupmanager.sh job.position=0 job.schedule="0 * * * *"
time="2024-02-09T08:00:06-06:00" level=error msg="error running command: exit status 1" iteration=6 job.command=/backupmanager.sh job.position=0 job.schedule="0 * * * *"`

 I had forgot however about binding over the top of the file, so this does indeed correct the issue. Thanks again.

**Comment by jammsen** [comment]
Well this was a known bug and already fixed for days on develop and yesterday published on to master/latest.

See: https://github.com/jammsen/docker-palworld-dedicated-server/commit/f30bef17edfd9fba390f6c0b6e4256ec45a6069d#diff-3b41cd2eeb76ac64c4b71b9cc6b253b358ab737f50d54e333b631ca27357e98eL54

So if you set your setting to manual and the RCON_ENABLE isnt set in Docker-Compose, the default set will catch in the Dockerfile, where RCON_ENABLE=false, therefore not sending messages.

**Comment by robertlane** [comment]
I've pushed the new image and agree we are good to call this solved.

**Comment by jammsen** [comment]
If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
