### ISSUE TITLE
How to use your Steam account when downloading game files

### ISSUE THREAD

**Issue by ethereal85** [jammsen/docker-palworld-dedicated-server#219]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

You can't connect using an anonymous login, but your own Steam account can

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by ethereal85** [comment]
The default account for this login is anonymous，how to change the account?

**Comment by jammsen** [comment]
> The default account for this login is anonymous，how to change the account?

That function isnt added because you should not need it. 

The error looks like you loose connection to the steam servers, not that you need a login.

https://www.google.com/search?q=steamcmd+has+been+disconnected+from+steam+with+result+3+%28no+connection%29&sca_esv=4d57ec59c228cf0f&rlz=1C1GCEA_enDE1086DE1086&sxsrf=ACQVn09YhACXs3LPH-Z93PydK13Ysty6AQ%3A1708709754202&ei=etfYZc35C7SNkdUPhIG8WA&oq=steamcmd+has+been+disconnected+from+&gs_lp=Egxnd3Mtd2l6LXNlcnAiJHN0ZWFtY21kIGhhcyBiZWVuIGRpc2Nvbm5lY3RlZCBmcm9tICoCCAAyBRAAGIAEMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgsQABiABBiKBRiGAzILEAAYgAQYigUYhgMyCxAAGIAEGIoFGIYDMgsQABiABBiKBRiGAzILEAAYgAQYigUYhgNIih5QngVYiwxwAXgAkAEAmAFfoAG7BKoBATe4AQPIAQD4AQHCAgoQABhHGNYEGLADiAYBkAYG&sclient=gws-wiz-serp

**Comment by jammsen** [comment]
Im closing this issue as inactive, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
