### ISSUE TITLE
[Bug Report] Can't start docker container on Synology server anymore.

### ISSUE THREAD

**Issue by Canoobi** [jammsen/docker-palworld-dedicated-server#274]
### You understand that if you dont provide clear information on your "Problem", "Software and Hardware-Setup" and the "Steps to reproduce" your issue will be closed without any help, because your not willing to do your part?

- [X] Yes i do!

### You understand that im not a Game-Dev or Game-Server-Dev and my support is primary for the Docker-Image and somewhat limited to the Game-Server?

- [X] Yes i do!

### Current behavior

When I try to start the container of the server on my Synology NAS, the server is crashing instantly and there is the following error:
`[91m>>> This Docker-Container must be run as root! Please adjust how you started the container, to fix this error.[0m`

I tried to start the server via GUI, ssh (with root-permissions) and root-script.

### Desired behavior

That the server starts normal.

### Steps to reproduce

Try to start a plaworld-server container on Synology NAS

### Software setup

- OS: Linux
- Docker: Container Manager 20.10.23-1437

### Hardware setup

- vCPU: AMD Ryzen R1600
- RAM: 64GB DDR4 3200 MHz
- Disk: Samsung 870 EVO 8TB

**Comment by jammsen** [comment]
Hello @Canoobi - Try asking people in Discord about this. The Error-Message was added for QNAP and Synology NAS'ses because they had problems switching users and stuff. You need to be root inside the Docker-Container to make sure all the permissions in the entrypoint-script are working, which are in-itself workarounds for Synology and QNAP NAS workarounds. Im not sure how you started this. i dont own prebuild NAS to test it on it.

**Comment by jammsen** [comment]
Closed because of inactivity
