### ISSUE TITLE
Running this on a NAS without Steam

### ISSUE THREAD

**Issue by kryst4line** [jammsen/docker-palworld-dedicated-server#3]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

First of all this is more of a question than an actual issue, sorry about that.

My goal is to run a Palworld dedicated server on my NAS, but in the code I'm seeing references to steam itself; am I supposed to install Steam as well?

### Desired behavior

Run a server on my NAS

### To Reproduce

-

### Software setup

- OS: DSM 7.2-64570 Update 1
- Docker: 20.10.23

### Hardware setup

-

**Comment by Catsanova** [comment]
You don't need to install Steam, the container includes SteamCMD. I gotten this working on a QNAP NAS without changing anything.

**Comment by jammsen** [comment]
What @Catsanova wrote is accurate, thanks!

**Comment by chsoriano** [comment]
I'm trying to get this running on a QNAP NAS also. I've created firewall rules on my gateway (Unifi) but the container still reboots with error: Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again. (screenshot below)

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/83658642/eadb94e5-8972-4ae7-8d4a-db32a2e19bd4)

**Comment by jammsen** [comment]
Then your container isnt online, SteamCMD always auto-updates itself and then downloads the package you require.

**Comment by jammsen** [comment]
Hey @kryst4line 
is your question answered and can this issue be closed?

**Comment by Luosuu** [comment]
@Catsanova Would you like to publish a detailed tutorial for how to run this on QNAP? Thank you very much! Should I use the container station app to pull & run this directly?

**Comment by kryst4line** [comment]
@jammsen Thanks for the response, will try again with your image today! Feel free to close, if I find any issue that it's not reported will make another post if that's better for you

**Comment by disfluxly** [comment]
@Luosuu - I'm also running this on a QNAP NAS, specifically the TS-251+ model (which is almost 10 years old).

It's extremely simple to setup. Just run the container directly through Container Station. Use the advanced configuration to make sure to set the port mapping for 8211:8211 via NAT. Also make sure to fill in all the Environment Variables that can be seen on this repo's README. By default it wants to use a Docker volume. I changed this to use a host binded volume instead, so that I can possibly use a different device to run the server without losing any of the existing data. 

After it's running, just make sure to port forward 8211 to your NAS on your router if you want to open it up to the internet.

Generally for connectivity, I recommend setting the community server setting to false. It's pretty impossible to find anything in the community server right now. Set up Dynamic DNS and use that in the Public IP portion of the Env Var. Don't set a server password (since a direct connection doesn't prompt for a password, and the recent lobby trick of seeing previously attempted connections doesn't seem to be working with how overloaded their backend servers are).

For performance, I would say it's _not great_, but I am on a near 10 year old NAS. I get between 20-30 Server FPS with 2-4 people playing on it. 

I'm curious which QNAP NAS @Catsanova has and what Server FPS they're getting, as I was looking to upgrade my unit anyways.

**Comment by Luosuu** [comment]
@disfluxly Thank you so much! I will git it a try on my one later. My one is a TS-563 which is almost 10 year old (made in 2015/2016) 😢

**Comment by liamsphin** [comment]
> @Luosuu - I'm also running this on a QNAP NAS, specifically the TS-251+ model (which is almost 10 years old).
> 
> It's extremely simple to setup. Just run the container directly through Container Station. Use the advanced configuration to make sure to set the port mapping for 8211:8211 via NAT. Also make sure to fill in all the Environment Variables that can be seen on this repo's README. By default it wants to use a Docker volume. I changed this to use a host binded volume instead, so that I can possibly use a different device to run the server without losing any of the existing data.
> 
> After it's running, just make sure to port forward 8211 to your NAS on your router if you want to open it up to the internet.
> 
> Generally for connectivity, I recommend setting the community server setting to false. It's pretty impossible to find anything in the community server right now. Set up Dynamic DNS and use that in the Public IP portion of the Env Var. Don't set a server password (since a direct connection doesn't prompt for a password, and the recent lobby trick of seeing previously attempted connections doesn't seem to be working with how overloaded their backend servers are).
> 
> For performance, I would say it's _not great_, but I am on a near 10 year old NAS. I get between 20-30 Server FPS with 2-4 people playing on it.
> 
> I'm curious which QNAP NAS @Catsanova has and what Server FPS they're getting, as I was looking to upgrade my unit anyways.

I'm probably just plain dumb... but I can't seem to get this to work at all. I can play locally via local ip, but anyone not in my network can't get in. I swear I've set like ports opened to the world... any chance you can like teamsviewer and help me set this NAS Container up?

**Comment by liamsphin** [comment]
> @Catsanova Would you like to publish a detailed tutorial for how to run this on QNAP? Thank you very much! Should I use the container station app to pull & run this directly?

Did you figure this out by any chance on your QNAP? I pull the container, installed, but can't seem to get into the game. Ran into the same Steam not online. I'm assuming it has something to do with the virtual switch being created and having no access to the internet. When I bridge it, it gives me access, but I can only join locally (no one else can join publicly).

**Comment by reedickulus** [comment]
> I'm trying to get this running on a QNAP NAS also. I've created firewall rules on my gateway (Unifi) but the container still reboots with error: Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again. (screenshot below)
> 
> ![image](https://private-user-images.githubusercontent.com/83658642/298245126-eadb94e5-8972-4ae7-8d4a-db32a2e19bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MjU3NDIsIm5iZiI6MTcwNzYyNTQ0MiwicGF0aCI6Ii84MzY1ODY0Mi8yOTgyNDUxMjYtZWFkYjk0ZTUtODk3Mi00YWU3LThkNGEtZGIzMmEyZTE5YmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA0MjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNDEyNDcxZmY0YTVmNWY1MGE3YjM4NGVjYTMyNzNiMDNkMTEzZDY5ZGE5OGZjYzM2NzFlZWU1ZjY0YTA3ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fvMZc6RdJOGBePgAQIYa4Bzgqnz3jNirf-H6sivdxV8)

I am getting the same error message - did you find a fix?
