### ISSUE TITLE
Using with XBMC version of the game

### ISSUE THREAD

**Issue by cyrrelsneer** [jammsen/docker-palworld-dedicated-server#48]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Sorry this is probably not the appropriate way to ask - but can this be used with the XBMC version of the game or only as long as it has the same version? Could a specific version be enforced to keep it alive in case XBMC version is behind?

### Desired behavior

as above

### To Reproduce

./

### Software setup

./

### Hardware setup

./

### Additional context

please delete if that is the wrong place please, don'T want it to be a burden for you guys

**Comment by ComputersWithTimo** [comment]
Palworld uses Epic Online Services (EOS) for Multiplayer.
That also includes the console version.

Since the server browser is currently broken, as long as you can directly connect using the IP-Address, this docker image should work.
It's on the "Community" tab at the bottom. I can add a screenshot later.

If you want to stay on an older version, just set the environment variable:
`ALWAYS_UPDATE_ON_START=false`
https://github.com/jammsen/docker-palworld-dedicated-server#environment-variables

Updates are downloaded through steam, so once you decide to update, it will pull the current steam version.

**Comment by cyrrelsneer** [comment]
thanks so much! highly appreciated. Will check it out later today then

**Comment by ComputersWithTimo** [comment]
Hey @cyrrelsneer i found a reply in a different issue where it says XBOX and Steam version aren't compatible yet.

https://github.com/jammsen/docker-palworld-dedicated-server/issues/6#issuecomment-1902115247

Weird thing since they use EOS. Shouldn't be too complicated to implement

**Comment by cyrrelsneer** [comment]
what a pitty, but thanks for the headsup

**Comment by jammsen** [comment]
> Sorry this is probably not the appropriate way to ask - but can this be used with the XBMC version of the game or only as long as it has the same version? Could a specific version be enforced to keep it alive in case XBMC version is behind?

Sorry im confused you mean XBOX right? My brain jumped instantly to Kodi and was very confused.

**Comment by cyrrelsneer** [comment]
haha sorry, yeah XBMC is something different ;-)
I was talking about the xbox gamepass version. sorry for the confusion!

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to try it out and reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
