### ISSUE TITLE
[Bug Report] Other variables in PalWorldSettings.ini will be set to DEFAULT after `docker compose restart`

### ISSUE THREAD

**Issue by narwhrl** [jammsen/docker-palworld-dedicated-server#73]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I directly modify PalWorldSettings.ini in mounted folder instead of using `docker exec`. If I modify the variables that is not specified in docker-compose.yml (like `DeathPenalty`), these variables will be set to default value after I execute `docker compose restart`.

### Desired behavior

I wish other variables can be left remain unchanged, or I can't restart the compose after I changed server settings.

### Links to screenshots

none

### To Reproduce

1. Use vim/nano to modify `GameDir/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` variables that is not specified in `docker-compose.yml`
2. docker compose restart
3. Use vim/nano to check `GameDir/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`, the variables just modified has been reverted to default value.

### Software setup

- OS: Ubuntu 20.04 LTS
- Docker: latest

### Hardware setup

- vCPU: 4 core
- RAM: 8GB
- Disk: 100GB

**Comment by challi1337** [comment]
The updated image has everything added into env variables in the docker compose, if you adjust that you won't have that issue anymore

**Comment by jammsen** [comment]
Hey @narwhrl

Yes @challi1337 is right, we had yesterday a massively giant update on request of the community that every setting should be setup by ENV vars, please look at the new and improved readme with alle the examples. Im fixing right now a bug in a few Regex's but the change should be live in about 30m.

Feel free to change this and test it and give me feedback later.

**Comment by narwhrl** [comment]
> Hey @narwhrl
> 
> 
> 
> Yes @challi1337 is right, we had yesterday a massively giant update on request of the community that every setting should be setup by ENV vars, please look at the new and improved readme with alle the examples. Im fixing right now a bug in a few Regex's but the change should be live in about 30m.
> 
> 
> 
> Feel free to change this and test it and give me feedback later.

Thanks for your contribution!

**Comment by jammsen** [comment]
The fix is live, feel free to try it.



> Thanks for your contribution!

Im happy to help ❤️

**Comment by jfstn** [comment]
@jammsen Are you sure the Dockefile is setting the ENV correctly? I believe that Dockerfile is missing many entries on `ENV` compared to what can supposedly be set.

**Comment by sirrkitt** [comment]
I just responded to this on another post but I'll mention it again:

If you want to use a static config file instead of env variables, you need to copy the config file somewhere else, edit it, and then mount it into the container as read-only:

`-v /srv/services/palworld/config/PalWorldSettings.ini:/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini:ro`

syntax:
-v means mount a volume, then:
the first half is the path to the file on your server, then a colon, then the path/file inside the container, then another colon, then **ro**, to say that the file shows up in the container as read-only.

On my setup I mount /srv/services/palworld/data to /palworld and then I mount /srv/services/palworld/config/PalWorldSettings.ini over the config file as read-only. Container will complain that it can't edit/modify the file but it loads it and starts, anyway.

**Comment by jammsen** [comment]
> @jammsen Are you sure the Dockefile is setting the ENV correctly? I believe that Dockerfile is missing many entries on `ENV` compared to what can supposedly be set.

Yes it does, i tested it many times and yes thats on purpose. The Dockerfile contains the abosultely minimal setup and in the Docker-Compose examples you can setup every setting known.

**Comment by jammsen** [comment]
@narwhrl - Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
