### ISSUE TITLE
[Feature Request]  希望添加一个环境变量设置不改变容器内的PalWorldSettings.ini Hope to add an environment variable setting that does not change the PalWorldSettings.ini inside the container

### ISSUE THREAD

**Issue by xy3xy3** [jammsen/docker-palworld-dedicated-server#95]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

I hope to add an environment variable setting that does not change the PalWorldSettings.ini inside the container. I prefer to make modifications on my own in the mounted directory, rather than modifying settings through Docker's environment variables

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by sirrkitt** [comment]
In Podman, but I think this works in Docker, too, you can just copy the config file somewhere, make your edits, and then mount it into the container as read-only. On this container specifically, it just complains about not being able to edit the config and then continues and loads it anyway.

This is the option I use for my specific setting:

`-v /srv/services/palworld/config/PalWorldSettings.ini:/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini:ro`

**Comment by jammsen** [comment]
Hey @xy3xy3 
thanks for the feature request. When i understand you correctly you want me to add a "dumb/manual" mode right?
Other people kinda refered to some things and asked this question many times but never got a clear answer.

The solution i offer right now is just the "Docker-Best-Practice" way and kinda the "12 Factor App" way, BUT that doesnt mean we cant support both, but nobody wanted that really and therefore no testers were available for this type of soltuion.

That is, IF i understand your request even correctly.

@sirrkitt - I wouldnt use a "hack" to solve a problem ... most of the time the problems get bigger and sometimes out of control, so please dont give thoose type of recommendations, before even asking me if im willing to not change that. Because i would be willing .... as i already wrote 😄
